spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/file
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true       # hibernate가 만들어준 sql을 로그에 표시
        use_sql_comments: true # sql문 주석으로 추가하여 표시해줌

  profiles:
    include:
    - oauth
    - aws

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: deshin-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
